---
title: "インストール"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

こちらでは、RとRStudioを自身のパソコンにインストールする方法を概説します。

## Rのインストール

【重要】Rを過去にインストール済である方も、インストールされているRのバージョンが古い(R 3.?.? 等)場合には各種コードで動作が異なったりエラーが出ることがありますので、以下の方法にて最新バージョンをインストールしてください（比較的最近のバージョン R 4.5.? や R 4.4.? や R 4.3.? ならおそらく問題ありません）。

Rのインストール方法はインストールするパソコンのOS(Windows/Mac)に依存します。

### Windowsの場合

Step.1： [install R for the first time](https://cran.r-project.org/bin/windows/base/)から"Download R-4.5.2 for Windows"をクリックして"R-4.5.2-win.exe"をダウンロードする。

Step.2： ダウンロードした"R-4.5.2-win.exe"を開くと「このアプリがデバイスに変更を加えることを許可しますか」と書かれたウィンドウが現れるので、「はい」をクリックする。

Step.3： 「セットアップに使用する言語の選択」と上に書かれたウィンドウが現れるので、日本語が選択されていることを確認して下の「OK」をクリックする。

Step.4： 「R for Windows 4.5.2 セットアップ」と上に書かれたウィンドウが現れるので、下の「次へ」を何度かクリックしていき、最後に下に現れる「完了」をクリックするとインストールが完了する。

【上手くいかないとき】MicrosoftのクラウドサービスであるOneDriveに"R-4.5.2-win.exe"をダウンロードして実行するとインストールできないことがあります。その場合は、"R-4.5.2-win.exe"をOneDriveからコンピュータ内のローカルフォルダへと移してからStep.2以降を再度試してください。

### Macの場合

Step.1： [Apple シリコン搭載の Mac コンピュータ](https://support.apple.com/ja-jp/116943)を参考に、インストールするMacコンピュータがAppleシリコン搭載かIntelプロセッサ搭載かを確認する。

Step.2： [R for macOS](https://cran.r-project.org/bin/macosx/)から、Appleシリコン搭載の場合は"R-4.5.2-arm64.pkg"を、Intelプロセッサ搭載の場合は"R-4.5.2-x86_64.pkg"をクリックして当該ファイルをダウンロードする。

Step.3： ダウンロードしたpkgファイルを「アプリケーションで開く：Installer」で開くと「Install R 4.5.2 for macOS」と上に書かれたウィンドウが現れるので、下に現れる「Continue(続ける)」「Agree(同意する)」「Install(インストール)」を何度かクリックしていき、最後に下に現れる「Close(閉じる)」をクリックするとインストールが完了する。

## RStudioのインストール

RStudioのインストール方法もインストールするパソコンのOS(Windows/Mac)に依存します。

### Windowsの場合

Step.1： [Download the RStudio Desktop](https://posit.co/download/rstudio-desktop/#download)から"DOWNLOAD RSTUDIO DESKTOP FOR WINDOWS"をクリックして"RStudio-2025.09.2-418.exe"をダウンロードする。

Step.2： ダウンロードした"RStudio-2025.09.2-418.exe"を開くと「このアプリがデバイスに変更を加えることを許可しますか」と書かれたウィンドウが現れるので、「はい」をクリックする。

Step.3： 「RStudio セットアップ」と上に書かれたウィンドウが現れるので、下に現れる「次へ」「インストール」を何度かクリックしていき、最後に下に現れる「完了」をクリックするとインストールが完了する。

### Macの場合

Step.1： [Download the RStudio Desktop](https://posit.co/download/rstudio-desktop/#download)から"RStudio-2025.09.2-418.dmg"をクリックして当該ファイルをダウンロードする。

Step.2： ダウンロードしたファイルを「アプリケーションで開く：DiskImageMounter」で開くと、"RStudio.app"アイコンと"Applications"へのショートカットアイコンの入ったフォルダ(Finder)が開くので、"RStudio.app"アイコンを"Applications"へのショートカットアイコンへとドラッグする。

## RStudioの起動

RとRStudioのインストールが完了しましたら、アプリケーションからRStudioを見つけてクリックし、RStudioを起動させてください。
